Used Software
=============


== Globally used Software ==

The following section lists and describes the software used commonly on all clouds.

=== Application ===

The application is written in python and builds upon the http://flask.pocoo.org/[Flask Framework].
To extend the usage, we've used a few flask extensions (available via "pip install <name>"):

* flask-login (Provides user session management)
* flask-sqlalchemy (Adds support for SQLAlchemy, a Python SQL Toolkit and Object-Relational-Mapper)
* flask-wtf (Allows to use http://wtforms.readthedocs.org/en/latest/[WTFForms])
* flask-oauthlib (Replaces flask-oauth by giving access to a newer version of the https://github.com/idan/oauthlib[oauthlib])

Also, we had to install a few additional python libraries independent of flask:

* sqlalchemy-migrate (Provides a way to manage database schema changes)
* pymysql (Enables the use of mysql in flask-sqlalchemy on clouds that don't have a direct way to access mysql)
* python-etcd (Provides access to etcd clusters from python)
* grequests (Asynchronous requests with gevent)


The flask application connects to a database to store user information. We chose mysql because it runs on all three clouds and is easily accessible via python/sqlalchemy.

As a backbone for the group communication we decided to use https://github.com/coreos/etcd[etcd]. It is a distributed, consistent key-value store.
We use it to decide when to add users to the database, when to write files and to synchronize those tasks between the different clouds.


=== Deployer ===

The deployer is written in python (requires the use of python 2.7) and has no additional requirements.
The different cloud-scripts may add requirements though.


== Cloud-specific Software ==

This section lists additional software used by the specific clouds.

=== Azure ===

==== Application ====

Azure also requires the "azure" python package for file storage access.

==== Deployer ====

The azure deployer script requires git to be installed. It needs to be in the PATH so that the script can easily call it.

=== AWS ===

==== Application ====

==== Deployer ====


=== Google ===

==== Application ====

==== Deployer ====
