"""Added some table 3

Revision ID: 17e72a182c73
Revises: 4b669ed496aa
Create Date: 2015-05-25 19:40:51.213354

"""

# revision identifiers, used by Alembic.
revision = '17e72a182c73'
down_revision = '4b669ed496aa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
