"""Added test column

Revision ID: 4d6ed425c3d8
Revises: 17e72a182c73
Create Date: 2015-05-25 19:41:49.840032

"""

# revision identifiers, used by Alembic.
revision = '4d6ed425c3d8'
down_revision = '17e72a182c73'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test2', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test2')
    ### end Alembic commands ###
