Load Balancing
==============

== Introduction ==

For the application we wanted useful load balancing, so that we only have one entry point. This entry point is supposed to balance the load to the different clouds. All of this should happen without the user even noticing it.
To achieve that, we thought about using nginx. Nginx is a reverse proxy, which natively supports load balancing.
Nginx supports three different types of load balancing:

* *round-robin* Standard. Requests to the application servers are distributed in a round-robin fashion
* *least-connected* next request is assigned to the server with the least number of active connections
* *ip-hash* a hash-function selects the server by hashing the IP of the request

We chose ip-hash because it makes sure that your sessions work. If you get routed to a different server for each request, your sessions might get lost and you may need to do everything all over again.

As an example, we're running the nginx server on aws, but it can be run anywhere (google, azure or even self-hosted).

== Setup and configuration ==

=== AWS Instance ===

We've used a t2.micro instance for demonstration purposes.

* Log in to aws, click on EC2 Dashboard -> Instances -> Launch Instance.
* Follow the instructions for a Amazon Linux AMI image.
* ssh into the instance and install nginx (e.g. with "sudo yum install nginx")
* start the nginx server with "sudo service nginx start"
* Set up the following two configs, replace placeholders (everything in <>)
* restart the nginx server with "sudo service nginx restart"

=== Configs ===

See <<nginx.conf>> and <<amos1.conf>>

== Azure/nginx compatiblity workaround ==

While working on this, we encountered an issue with azure and nginx. Apparently, when using the "upstream" directive in nginx, nginx reads the URLs given at start, resolves them and then only uses the IP received by resolving the URL. However, azure requires requests to be sent using the URL, not only the IP (probably for their loadbalancer). This caused azure to always throw "404 - WebApp not found" errors.

We solved this by adding a second "server" keyword and telling it to handle the subdomain azure.<domain>.<tld>. Now, inside the "upstream" part, we told nginx to call the subdomain instead of azure directly. This subdomain now calls azure using proxy_pass, which somehow does not call by IP but always by URL.

This solved the issue. So, if, for whatever reason, the upstream way does not work directly, just add another server {} part, similar to the azure one, and replace the upstream -> server by the same string you add in server -> server_name.

We also did the same for AWS, because we don't know if AWS does load balancing via URL or via IP internally. Using the URL instead of the IP definitely works.

== Appendix ==

[[nginx.conf]]
./etc/nginx/nginx.conf

----

user  nginx;
worker_processes  2;

error_log  /var/log/nginx/error.log;
#error_log  /var/log/nginx/error.log  notice;
#error_log  /var/log/nginx/error.log  info;

pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    gzip  on;
    gzip_disable "msie6";

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    index   index.html index.htm;
}
----

[[amos1.conf]]
./etc/nginx/conf.d/amos1.conf

----
upstream amos1 {
    ip_hash;
    server azure.<your_domain>;
    server aws.<your_domain>;
    server <googledomain>;

}
server {
    listen 80;

    server_name <your_domain>;

    location / {
        proxy_pass http://amos1;
    }
}

server {
    listen 80;
    server_name azure.<your_domain>;

    location / {
        proxy_pass http://<azure_domain>;
    }
}

server {
    listen 80;
    server_name aws.<your_domain>;
    
    location / {
        proxy_pass http://<awsdomain>;
    }
}
----
